project:
  type: website
  output-dir: docs

website:
  title: "The Digital Tourist: Speed in China"
  navbar:
    left:
      - href: index.qmd
        text: "The Data Story"
      - href: slides.qmd
        text: "Presentation (Slides)"
      - href: about.qmd
        text: "Methodology (Appendix)"
    right:
      - icon: github
        href: https://github.com/LZR-ops/ishowspeed_NLP_Project
        text: Source Code

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-title: "Story Contents"
    code-fold: true      # Allows curious readers to see code if they click
    code-tools: true     # Adds a "View Source" button
    smooth-scroll: true

# GLOBAL EXECUTION OPTIONS
# This section ensures the handbook requirement: 
# "The report must be readable without reading code."
execute:
  echo: false      # Hides code chunks by default in the output
  warning: false   # Hides Python warnings/errors
  freeze: auto     # Saves time by not re-running code if nothing changed